name: Maltex
options:
  bundleIdPrefix: app.maltex.native
  indentWidth: 4
  tabWidth: 4

packages:
  Aria2Kit:
    url: https://github.com/baptistecdr/Aria2Kit
    version: 1.0.4
  AnyCodable:
    url: https://github.com/Flight-School/AnyCodable
    version: 0.6.7
  Alamofire:
    url: https://github.com/Alamofire/Alamofire
    version: 5.11.0

targets:
  Maltex:
    type: application
    platform: macOS
    deploymentTarget: "14.0"
    sources:
      - path: Maltex
      - path: extra/darwin/arm64/engine/aria2c
        type: file
        buildPhase: resources
      - path: extra/darwin/arm64/engine/aria2.conf
        type: file
        buildPhase: resources
    settings:
      base:
        INFOPLIST_FILE: Maltex/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: app.maltex.native
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        SWIFT_VERSION: 6.2
        MARKETING_VERSION: 0.8.3
        CURRENT_PROJECT_VERSION: 830
        ENABLE_HARDENED_RUNTIME: YES
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: ""
    dependencies:
      - package: Aria2Kit
      - package: AnyCodable
      - package: Alamofire
      - target: Maltex Extension

  Maltex Extension:
    type: app-extension
    platform: macOS
    deploymentTarget: "14.0"
    sources:
      - path: MaltexExtension
    settings:
      base:
        INFOPLIST_FILE: MaltexExtension/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: app.maltex.native.extension
        GENERATE_INFOPLIST_FILE: NO
        SWIFT_VERSION: 6.2
        MARKETING_VERSION: 0.8.3
        CURRENT_PROJECT_VERSION: 830
        ENABLE_HARDENED_RUNTIME: YES
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: ""
    dependencies: []
    